### ISSUE TITLE
this.sql`SELECT...` not get highligted

### ISSUE THREAD

**Issue by michael-land** [frigus02/vscode-sql-tagged-template-literals#7] opened 2020-05-13 08:09 UTC
I'm using nestjs with postgres, and inject sql function

```
@Injectable()
export class SomeService {
  constructor(
    @InjectPostgres() private readonly sql: Postgres
  ) {}

  method(){
    this.sql`SELECT *...`;
  }
```

Expected this.sql also get syntax highlighted

**Comment by frigus02** [comment] 2020-05-17 10:35
This is an interesting bug. I don't understand what's going on, yet. I tried the following snippets.

Syntax highlighting broken:
```ts
class SomeService {
  method() {
    this.sql`SELECT * FROM users`;
  }
}
```

Syntax highlighting works:
```ts
class SomeService {
  sql(s: TemplateStringsArray, ...values: any[]) {}

  method() {
    this.sql`SELECT * FROM users`;
  }
}
```

**Comment by frigus02** [comment] 2020-05-17 10:57
Hm, the extension seems to mess up the standard TypeScript syntax highlighting.

With the extension:
![image](https://user-images.githubusercontent.com/3579251/82142598-5bdb2a80-9835-11ea-9bc5-21cbace129b3.png)

Without the extension:
![image](https://user-images.githubusercontent.com/3579251/82142604-72818180-9835-11ea-967f-8385ca4a97f4.png)

Both `this` and the dot after it are not highlighted when the extension is enabled.

Tested in VS Code 1.45.1

**Comment by frigus02** [comment] 2020-05-17 12:11
I think the grammar for function calls was outdated and also not entirely correct. It looks slightly better after updating, but doesn't quite work, yet. Takes me a while to understand this monster of a regular expression. 😅

**Comment by frigus02** [comment] 2021-01-15 17:32
I just updated the grammar again. As far as I can see this fixes the issue. I'm not able to reproduce the broken behaviour anymore.

<img width="602" alt="grafik" src="https://user-images.githubusercontent.com/3579251/104759176-d14e2080-575f-11eb-800c-6909d3a5e217.png">

I'm going to close this issue for now. But feel free to reopen if you're still seeing the issue.

**Closed as completed by frigus02** 2021-01-15 17:32 UTC
Labels: bug
